name: Heuro
markdown: redcarpet
pygments: true

assets:
  compress:
    css: sass
    js:  uglifier

sass:
  sass_dir: _sass
  style: :compressed

exclude: [todo.md, publish.sh, compass.rb, config.ru, Gemfile,
  Gemfile.lock, Procfile, Rakefile, README.md, sass, unicorn.rb, vendor, bin]

permalink: articles/:title

cdn: http://www.heuro.net
url: http://www.heuro.net