name: Heuro
pygments: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

assets:
  sources:
    - _assets
    - _assets/data
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  compress:
    css_compressor: sass
    js_compressor:  uglifier

sass:
  style: :compressed

exclude: [todo.md, publish.sh, compass.rb, config.ru, Gemfile, Guardfile,
  Gemfile.lock, Procfile, Rakefile, README.md, sass, unicorn.rb, vendor, bin,
  s3_website.yml, .gitignore, .env, analysis]

permalink: :categories/:title

cdn: http://www.heuro.net
url: http://www.heuro.net